config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  
  get 'welcome/index'

  get '/signup',         to: 'users#new'
  post '/signup',        to: 'users#create'

  get '/login',         to: 'sessions#new'
  post '/login',        to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		This app was developed by the Mines chapter of the Association of Computing Machinery and is powered by Ruby on Rails.
	</small>
	<br>
<div class="logos">
<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

<%= link_to image_tag("ACM-logo.png", alt: "ACM logo"),
            'http://acm.org/' %>

<%= link_to image_tag("mines_EEE.png", alt: "CSM logo", id: "mines_logo"),
            'http://mines.edu/' %>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Mines eSports Tournament Matching Tool", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home",   root_path %></li>
				<% if logged_in? %>
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
					<li><%= link_to "All Users", users_path %></li>
					<li><%= link_to "Log Out", logout_path, method: "delete" %></li>
				<% else %>
					<li><%= link_to "Log in", login_path %></li>
					<li><%= link_to "Register", signup_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= yield(:title) %> | eSportsMatcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
	  <% flash.each do |message_type, message| %>
		  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	  <% end %>

	  <%= yield %>
	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>